version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: blackjack
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: blackjackdb
    ports:
      - "5432:5432"
    volumes:
      # šita eilutė sujungia tavo projecto katalogą my_local_data
      # su Postgres data direktorija
      - ./my_local_data:/var/lib/postgresql/data
      # ir, jeigu reikia, lieka tavo init skriptai:
      - ./database:/docker-entrypoint-initdb.d

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      DATABASE_URL: postgres://blackjack:secret@db:5432/blackjackdb
      JWT_SECRET: slaptas_tokenas
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:5000
    command: npm run dev -- --host
