version: "3.8"

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: secret
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://appuser:secret@db:5432/appdb
      JWT_SECRET: slaptas_tokenas
    depends_on:
      - db
